name: "John Children"
description: "A personal website"
author: "John Children"

url: "http://jchildren.github.io/"

markdown: rdiscount
permalink: pretty

highlighter: pygments
github: [Repository metadata]

paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: ""
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "default" # overrides previous default layout
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: "blog"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      layout: "default" # overrides previous default layout
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "default" # overrides previous default layout
