name: "John Children"
description: "A personal website"
author: "John Children"

url: "http://jchildren.github.io/"

markdown: rdiscount
permalink: pretty

highlighter: pygments
github: [Repository metadata]
pagination: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
