name: "John Children"
description: "A personal website"

url: "http://jchildren.github.io/"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true

highlighter: pygments
github: [Repository metadata]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
