# Site settings
title: jchildren.github.io
email: j.a.children@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  24 year old physics MSc graduate, working as a web developer in Vancouver.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.john-children.com" # the base hostname & protocol for your site
twitter_username: john_children
github_username:  jchildren
linkedin_username: johnchildren

# Build settings
markdown: kramdown
